### ISSUE TITLE
emerge: There are no ebuilds to satisfy "zlib"

### ISSUE THREAD

**Issue by BalaMuthusamy** [frogbywyplay/genbox_ov-host-st#1]
When running emerge --fetchonly zlib, there is an error, but can't find supporting document on how to resolve it?

I had been following the entire setup process as per:
https://portal.frogbywyplay.com/docs/wytv/2.0.1.2.2/frog-genbox/guide-install/#genbox-installing

At the very last, the instructions are to perform: emerge --fetchonly zlib

Here is the entire output:
emerge --fetchonly zlib --verbose

Calculating dependencies -
emerge: there are no ebuilds to satisfy "zlib".

fyi, Ubunu info:
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty

Are there any suggestions / next steps?

**Comment by ghost** [comment]
Hello

Could you give more infos about the context and what you are trying to do?

you can do emerge -s "%zlib" to see first if the package is seen and exist.

You should get something like :  
-  sys-libs/zlib
    Latest version available: 1.2.3-r1
    Latest version installed: 1.2.3-r1
    Size of files: Unknown (missing digest for 'zlib-1.2.3.tar.bz2')
    Overlay:       /usr/portage
    Path:          /usr/portage/sys-libs/zlib/zlib-1.2.3-r1.ebuild
    Homepage:      http://www.zlib.net/
    Description:   Standard (de)compression library
    License:       ZLIB

Cheers
Marco

**Comment by BalaMuthusamy** [comment]
Marco:
Thank you for your fast and insightful response.
This step is part of the initial setup for the WyPlay genbox.  (The link for installation [and the requirement to run emerge command] was in the original query).

Running your command to see about the genbox installation does give the sys-libs/zlib, with same version but without the overlay and related details.  The output is towards the bottom of this message.

FYI: Even after running your command to ensure that the versions are okay, I still get the same error when running "emerge --fetchonly zlib".
Error message: "emerge: there are no ebuilds to satisfy "zlib"."

The message seems to indicate that it is something non-trivial, possibly some prior steps were missed out.  Is this error expected during the installation phase or is this a serious error? Also, what is the solution to overcome this error (if this is a crucial error)

Searching...  
[ Results for search key : zlib ]
[ Applications found : 5 ]
-  dev-perl/Compress-Raw-Zlib
    Latest version installed: 2.011
    Homepage:      http://search.cpan.org/search?query=Compress-Raw-Zlib&mode=dist
    Description:   Low-Level Interface to zlib compression library
    License:       || ( Artistic GPL-2 )
-  dev-perl/Compress-Zlib
    Latest version installed: 2.011
    Homepage:      http://search.cpan.org/search?query=Compress-Zlib&mode=dist
    Description:   A Zlib perl module
    License:       || ( Artistic GPL-2 )
-  dev-perl/IO-Compress-Zlib
    Latest version installed: 2.011
    Homepage:      http://search.cpan.org/search?query=IO-Compress-Zlib&mode=dist
    Description:   Read/Write compressed files
    License:       || ( Artistic GPL-2 )
-  dev-perl/IO-Zlib
    Latest version installed: 1.09
    Homepage:      http://search.cpan.org/~tomhughes/
    Description:   IO:: style interface to Compress::Zlib
    License:       || ( Artistic GPL-2 )
-  sys-libs/zlib
    Latest version installed: 1.2.3-r1
    Homepage:      http://www.zlib.net/
    Description:   Standard (de)compression library
    License:       ZLIB

**Comment by ptisserand** [comment]
Hi, 
did you follow the following part of genbox documentation: [Genbox prerequisites for frog](https://portal.frogbywyplay.com/docs/wytv/2.0.1.2.2/frog-genbox/guide-frog-setup/)

I'm wondering if your initial overlay sync (this is done after pasting your auth token) didn't failed.
You could check if you have contents in `/usr/portage` directory inside genbox.

If not, after you have correctly setup your SSH part, doing `emerge --sync` should fix your issue.

**Comment by BalaMuthusamy** [comment]
Are there access permissions to repositories that might need enabling or some privileges on the git itself?  I am thinking out aloud on possibilities and trying to brainstorm with experts on what could be going on.

To reply to your question: The /usr/portage has ONLY a .git directory, which contains files & dirs (pasted below):

But, still the emerge --sync fails with following error:
[SWOffice-1] genbox local # emerge --sync --verbose

> > > Updating main portage /usr/portage
> > > /usr/portage uses git for SCM
> > >   URI: git@github.com:frogbywyplay/genbox_ov-host.git
> > >   BRANCH: master
> > >   REVISION: None
> > > Syncing with GIT
> > > Doing update
> > > _fatal: bad revision 'HEAD'_
> > > _fatal: bad revision 'HEAD'_
> > > _fatal: Needed a single revision_
> > > You do not have the initial commit yet
> > > ERROR: Repository not found.
> > > fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
!!! git pull error; exiting.

FYI: Direcory structure under /usr/portage/
[SWOffice-1] genbox local # ls -al /usr/portage/.git/
total 40
drwxr-xr-x 7 root root 4096 2016-01-20 21:05 .
drwxr-xr-x 3 root root 4096 2016-01-20 18:15 ..
drwxr-xr-x 2 root root 4096 2016-01-20 18:15 branches
-rw-r--r-- 1 root root  209 2016-01-20 18:15 config
-rw-r--r-- 1 root root   73 2016-01-20 18:15 description
-rw-r--r-- 1 root root    0 2016-01-20 21:05 FETCH_HEAD
-rw-r--r-- 1 root root   23 2016-01-20 18:15 HEAD
drwxr-xr-x 2 root root 4096 2016-01-20 18:15 hooks
drwxr-xr-x 2 root root 4096 2016-01-20 18:15 info
drwxr-xr-x 4 root root 4096 2016-01-20 18:15 objects
drwxr-xr-x 4 root root 4096 2016-01-20 18:15 refs

**Comment by achataignier** [comment]
Hi,

If you have access problems to Github, you need to follow step by step the two following sections to configure Git access rights from your environment properly:

https://portal.frogbywyplay.com/docs/wytv/featured/frog-genbox/guide-frog-setup/#configuring-ssh-and-github-credentials

https://portal.frogbywyplay.com/docs/wytv/featured/frog-genbox/guide-frog-setup/#configuring-your-sudo-identity

Once done, you must resume the genbox installation at the following step:
https://portal.frogbywyplay.com/docs/wytv/featured/frog-genbox/guide-install/#frog-token

Kind regards
Arnaud.

**Comment by BalaMuthusamy** [comment]
Arnaud:
Two independent people, with two different systems, following the exact same steps and gotten blocked by the same problem.  I am wondering, if either I don't have access permissions / privileges OR may be the instructions for installation is incomplete? (FYI about privileges, under [https://github.com/frogbywyplay](https://github.com/frogbywyplay),  genbox_ov-host-st is the ONLY C++ entity.  Shouldn't I be seeing more?

Yes, all these steps have been performed.  For step 1, I did get confirmation about the "Hi <username>! You've successfully authenticated, but GitHub does not provide shell access."
For Step 2, I did add i and verified that the sudo echo $SSH_AUTH_SOCK works correctly AND the sudo visudo has been performed.  Corroborated it by opening up /etc/sudoers file also.  So, this step is also succesful.

Then the same issue still occurs:
[SWOffice-1] genbox / # emerge --sync --verbose

> > > Updating main portage /usr/portage
> > > /usr/portage uses git for SCM
> > >   URI: git@github.com:frogbywyplay/genbox_ov-host.git
> > >   BRANCH: master
> > >   REVISION: None
> > > Syncing with GIT
> > > Doing update
> > > fatal: bad revision 'HEAD'
> > > fatal: bad revision 'HEAD'
> > > fatal: Needed a single revision
> > > You do not have the initial commit yet
> > > ERROR: Repository not found.
> > > fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
!!! git pull error; exiting.

**Comment by ptisserand** [comment]
Hi,
you also need to remove /usr/portage directory since
portage version provided within genbox-0.9.1-20140514.2.run installer doesn't contains the following fix: https://github.com/frogbywyplay/genbox_portage/commit/e9855ddac6a0a49dc887e20d91445f522cf50de1

Please note that this fix is provided within frog 3.0.1 installer: https://portal.frogbywyplay.com/docs/wytv/3.0.1.9.7/frog-genbox/guide-install/

**Comment by BalaMuthusamy** [comment]
Yes, ptisserand, that had also been done previously, based on some of the details I had read online.  Still same issue.  Thank you for looking into this and supporting into this process.  Has anyone successfully completed this setup process recently in ubuntu?

Here are the details including the rm -f for /usr/portage
[SWOffice-1] genbox / # rm -fR /usr/portage/
[SWOffice-1] genbox / # emerge --sync --verbose

> > > Updating main portage /usr/portage
> > > /usr/portage not found, creating it.
> > > /usr/portage uses git for SCM
> > >   URI: git@github.com:frogbywyplay/genbox_ov-host.git
> > >   BRANCH: master
> > >   REVISION: None
> > > Syncing with GIT
> > > Doing initial import
> > > Initialized empty Git repository in /usr/portage/.git/
> > > Fetching origin
> > > ERROR: Repository not found.
> > > fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
!!! git remote failed !!![SWOffice-1] genbox / # emerge --sync --verbose

> > > Updating main portage /usr/portage
> > > /usr/portage uses git for SCM
> > >   URI: git@github.com:frogbywyplay/genbox_ov-host.git
> > >   BRANCH: master
> > >   REVISION: None
> > > Syncing with GIT
> > > Doing update
> > > fatal: bad revision 'HEAD'
> > > fatal: bad revision 'HEAD'
> > > fatal: Needed a single revision
> > > You do not have the initial commit yet
> > > ERROR: Repository not found.
> > > fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
!!! git pull error; exiting.

**Comment by ghost** [comment]
This is very strange!

On my side I can confirm the genbox setup installation is OK on Fedora and Ubuntu, tested on different setups without problems.

Could be nice to explain all your steps one by one to see what is different from us.

Cheers
Marco

**Comment by ghost** [comment]
Reading your past emails, I realized you are trying to install an old genbox.

On my side I used this URL :

https://portal.frogbywyplay.com/docs/wytv/featured/frog-genbox/guide-install/

Cheers
Marco

**Comment by ptisserand** [comment]
Hi BalaMuthusamy,
could you please try inside genbox the following commands:
1 # git clone git@github.com:frogbywyplay/genbox_ov-host-st.git
2 # git clone git@github.com:frogbywyplay/genbox_ov-host.git

It will allow to verify that your SSH connection is right.
`genbox_ov-host-st.git` is a **public** repository, so you should be able to clone it even in case of your github account doesn't correctly have frogbywyplay access.
`genbox_ov-host.git` is a **private** repository, so you will only be able to clone it if your github account have frogbywyplay access.

If 1 is KO => SSH authentication issue inside genbox
If 1 is OK and 2 is KO => frogbywyplay access issue
If 1 is OK and 2 is OK => really weird issue ;)

**Comment by gstephan** [comment]
Hi BalaMuthusamy, first sorry for not coming back to you earlier.
Indeed your issue looks like a problem with github authorization with the frogbywyplay organization.

I see that you initiated the github link from the Frogbywyplay account, but since a few month there is another step to do on the github side, which is to accept the invitation. You should have received an email from github, or you can accept the invitation from the https://github.com/frogbywyplay page.

(see https://github.com/blog/1868-inviting-people-to-your-organization )

**Comment by BalaMuthusamy** [comment]
Summary: Still not yet resolved.  Same problem continuing.

Gstephan:
I believe this could be the core issue.  I did receive the github link from FrogByWyPlay and registered immediately based on it.  I believe this was created by someone in your organization.  But, on the git projects screen, I see only the genbox_ov-host-st.git, but do no see ANY PRIVATE repos.  I believe we are on the right track, and **is there someone who can look into the account and find out why we do not see the private repos**?

ptisserano:
I followed your instruction, and we are at the "FrogByWyPlay access issue" problem, as you had listed.
The #1:  git clone git@github.com:frogbywyplay/genbox_ov-host-st.git   ==> SUCCESSFUL
The #2: git clone git@github.com:frogbywyplay/genbox_ov-host.git  ==> FAILURE.

Details:
[SWOffice-1] genbox / # git clone git@github.com:frogbywyplay/genbox_ov-host-st.git
Cloning into 'genbox_ov-host-st'...
remote: Counting objects: 764, done.
remote: Total 764 (delta 0), reused 0 (delta 0), pack-reused 764
Receiving objects: 100% (764/764), 3.13 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (363/363), done.
Checking connectivity... done.

[SWOffice-1] genbox / # git clone git@github.com:frogbywyplay/genbox_ov-host.git
Cloning into 'genbox_ov-host'...
ERROR: Repository not found.
fatal: *_Could not read from remote repository.
*_
Please make sure you have the correct access rights
and the repository exists.

Marco:
Quick summary: Not yet working.
Details: Based on your link: https://portal.frogbywyplay.com/docs/wytv/featured/frog-genbox/guide-install/, i have had a chance to download and install them.  (FYI, this was about a 2MB larger for the gen box installation).  The process resulted in the same problem.  emerge --sync still does not work.  It fails with the exact same messages.

**Comment by achataignier** [comment]
Hello, just figured out the root cause, the problem is on our side. Something went wrong in the rights management system, I gave instructions internally to fix this issue asap.  This is the first time this problem happens. Sorry for the inconvenience and the time spent on your side. We'll keep you posted once fixed.

Kind regards
Arnaud.

**Comment by achataignier** [comment]
Hi, this should be solved by now, the issue has been solved in our rights management system.

**Comment by BalaMuthusamy** [comment]
Thank you.  This is solved.  We can see the necessary contents through: https://github.com/frogbywyplay
